image: python:3.6-slim

stages:
  - test
  - build
  
variables:
  LUDUM_LATEST_IMAGE: $CI_REGISTRY_IMAGE/ludum

test:
  image: ejplatform/python:alpine
  stage: test
  script:
    - flake8 

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS

    - docker build -f Dockerfile -t $LUDUM_LATEST_IMAGE .
    - docker push $LUDUM_LATEST_IMAGE
  only:
    - /master/

build-dev:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS

    - docker build -f Dockerfile -t $LUDUM_LATEST_IMAGE:dev .
    - docker push $LUDUM_LATEST_IMAGE:dev
  only:
    - /development/

# build-action:
#   stage: build
#   image: docker:latest
#   services:
#     - docker:dind
#   script:
#     - docker login -u $DOCKER_USER -p $DOCKER_PASS

#     - docker build -f action.Dockerfile -t $LUDUM_ACTION_IMAGE .
#     - docker push $LUDUM_ACTION_IMAGE:dev
#   only:
#     - /development/