image: python:3.6-slim

stages:
  - test
  - build
  - build-dev
  
variables:
  LUDUM_LATEST_IMAGE: $CI_REGISTRY_IMAGE/ludum:latest

test:
  image: ejplatform/python:alpine
  stage: test
  script:
    - flake8 

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS

    - docker build -f Dockerfile -t $LUDUM_LATEST_IMAGE .
    - docker push $LUDUM_LATEST_IMAGE
  only:
    - /master/
  environment: production

build-dev:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS

    - docker build -f Dockerfile -t $LUDUM_LATEST_IMAGE .
    - docker push $LUDUM_LATEST_IMAGE
  only:
    - /development/
